# Generated by Django 5.1 on 2025-11-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_platillo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], default='Disponible', max_length=20)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
