# Generated by Django 5.1 on 2025-11-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible')], default='disponible', max_length=20),
        ),
    ]
